
 ######################################################################################
 ###  ██╗░░░░░██╗░██████╗░██╗░░██╗████████╗░██╗░░░░░░░██╗░█████╗░██╗░░░░░███████╗   ###
 ###  ██║░░░░░██║██╔════╝░██║░░██║╚══██╔══╝░██║░░██╗░░██║██╔══██╗██║░░░░░██╔════╝   ###
 ###  ██║░░░░░██║██║░░██╗░███████║░░░██║░░░░╚██╗████╗██╔╝██║░░██║██║░░░░░█████╗░░   ###
 ###  ██║░░░░░██║██║░░╚██╗██╔══██║░░░██║░░░░░████╔═████║░██║░░██║██║░░░░░██╔══╝░░   ###
 ###  ███████╗██║╚██████╔╝██║░░██║░░░██║░░░░░╚██╔╝░╚██╔╝░╚█████╔╝███████╗██║░░░░░   ###
 ###  ╚══════╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚══════╝╚═╝░░░░░   ###
 ######################################################################################
 # Связь с разработчиком:
 # VK - @lightwolf7
 # TG - @lightwolf

 # Команды:
 #   /forum register (пароль)
 #   /forum remove (никнейм)

 # Права на использование команд:
 #    lForum.remove - Использование команды /forum remove (никнейм)
 # Настройка префикса
  prefix: "&6&lФОРУМ&f&l: "
 # Сообщения
  message:
    notPlayer: "&c&lИзвините, но только игроки могут использовать эту команду!"
    invalidCommandUsage: "&c&lНеверное использование команды. Используйте: /forum register <пароль>"
    successfully: "&a&lРегистрация произошла успешно!"
    alreadyRegistered: "&c&lИзвините, но вы уже зарегистрированы!"
    databaseInit: "&c&lПроизошла ошибка при инициализации базы данных"
    databaseConnection: "&c&lПлагин не смог подключиться к базе данных. Пожалуйста, проверьте конфигурацию вашей базы данных."
    removeSuccess: "&a&lПользователь был успешно удален"
    removeNotFound: "&c&lИзвините, но пользователь не зарегистрирован на форуме!"
    noPermission: "&c&lИзвините, у вас недостаточно прав для использования данной команды!"
    MinlengthPassword: "&c&lИзвините, но ваш пароль должен состоять минимум из {minLength} символов"
    MaxlengthPassword: "&c&lИзвините, но ваш пароль должен состоять максимум из {maxLength} символов"


# Ограничение символов при регистрации

  password:
    minLength: 8
    maxLength: 16


# Подключение к базе данных MySQL

  database:
    host: "localhost"
    port: 3306
    name: "your_database_name"
    username: "your_username"
    password: "your_password"

